import Footer from "../components/Footer";
import Nav from "../components/Nav";

export const metadata = {
  title: "courses page",
  description: "Generated by create next app",
};

export default function CoursesLayout({ children }) {
  return (
    <div>
      <Nav />
      {children}
      <Footer />
    </div>
  );
}
