import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="mdl-js">
      <body className="relative bg-gradient-to-l from-[#1c1c1f] via-[#36363b] to-[#1c1c1f]">
        <div className="fixed inset-0 w-full h-full -z-50 overflow-hidden">
          <span
            className="absolute top-[80vh] left-[45vw] w-2.5 h-2.5 bg-gradient-to-br from-[#1c1c1f] via-[#35353a] to-[#1c1c1f] rounded-2xl shadow shadow-cyan-300
          animate-[cube_8s_ease-in_forwards_infinite]"
          ></span>
          <span
            className="absolute top-[40vh] left-[25vw] w-2.5 h-2.5 bg-gradient-to-br from-[#1c1c1f] via-[#35353a] to-[#1c1c1f] rounded-2xl shadow shadow-cyan-300 
          animate-[cube_8s_ease-in_forwards_1s_infinite]"
          ></span>
          <span
            className="absolute top-[50vh] left-[75vw] w-2.5 h-2.5 bg-gradient-to-br from-[#1c1c1f] via-[#35353a] to-[#1c1c1f] rounded-2xl shadow shadow-cyan-300 
          animate-[cube_8s_ease-in_forwards_2s_infinite]"
          ></span>
          <span
            className="absolute top-[10vh] left-[90vw] w-2.5 h-2.5 bg-gradient-to-br from-[#1c1c1f] via-[#35353a] to-[#1c1c1f] rounded-2xl shadow shadow-cyan-300 
          animate-[cube_8s_ease-in_forwards_3s_infinite]"
          ></span>
          <span
            className="absolute top-[85vh] left-[10vw] w-2.5 h-2.5 bg-gradient-to-br from-[#1c1c1f] via-[#35353a] to-[#1c1c1f] rounded-2xl shadow shadow-cyan-300 
          animate-[cube_8s_ease-in_forwards_4s_infinite]"
          ></span>
          <span
            className="absolute top-[10vh] left-[50vw] w-2.5 h-2.5 bg-gradient-to-br from-[#1c1c1f] via-[#35353a] to-[#1c1c1f] rounded-2xl shadow shadow-cyan-300 
          animate-[cube_8s_ease-in_forwards_5s_infinite]"
          ></span>
        </div>
        {children}
      </body>
    </html>
  );
}
